### ISSUE TITLE
[Possible Typo] CPU Profiler Table

### ISSUE THREAD

**Issue by raivatshah** [DataDog/go-profiler-notes#17]
Hey! 

Thanks for this amazing resource! Is there any chance there's a typo in the CPU Profiler stack trace? I'm guessing the `main.childWork` is possibly referring to `main.backgroundWork` ? Please correct me if I'm wrong! 
<img width="1084" alt="Screenshot 2022-08-11 at 2 04 18 PM" src="https://user-images.githubusercontent.com/29497717/184073387-88655493-83ce-4728-885c-0e39054cbc4b.png">

**Comment by felixge** [comment]
Sorry for the slow reply, my daughter was born on Aug 11, but now I'm back from my initial parental leave :).

Anyway, thank you for reporting this and paying close attention to details. You're completely right and I fixed the issue in the commit linked above.

**Comment by raivatshah** [comment]
Sorry for the late reply as well! Congratulations on the birth of your daughter!! Thanks so much for fixing the issue as well :)
