### ISSUE TITLE
Translation authorization

### ISSUE THREAD

**Issue by miranquil** [DataDog/go-profiler-notes#26]
Hi! Thank you for your great writing. I'm working around Golang profiling, and your articles helped me a lot!

Would you please allow me to translate your articles into Chinese and share these great content to more people? I would mark your name and source link of your repository if permitted.

And also, if you wish, I can make a PR after translation to provide markdown files in Chinese language to your own repository!

All in all, thank you for your kindness and hard working!

**Comment by felixge** [comment]
@miranquil thanks for reaching out! The [LICENSE](https://github.com/DataDog/go-profiler-notes/blob/main/LICENSE.txt) of this project allows translations. This [page](https://creativecommons.org/licenses/by-sa/4.0/deed.en) provides a simplified explanation of the rules. But from what you're saying, it sounds like you're planning to follow those rules? Or do you need any exception?

**Comment by miranquil** [comment]
@felixge Thank you. Of course I'm planning to follow. Thank you for your working again!
